# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fb5d5b87df5dd3c3d34fb34b966165bd262787d7108693bbeacdeddfbcc7b5f70d70db3a5a83b3b15181175817fcdb90de41f7d53abc4be664ed8a3661ddc0e

test:
  secret_key_base: ba1a7fdc3504efef89c2c7f7b51528e0253a4f462a88c9f12ece454d2343b05223f481a416e43c96372858e3aea4121bd7d437e13850089439fc24f4ca60d436

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
